### ISSUE TITLE
Token Issue

### ISSUE THREAD

**Issue by DylanNWatt** [nash-md/twilio-contact-center#1]
I've been attempting to get the demo up and running, but seem to be running into some issues with the initial configuration. I initially tried to set up the server locally. All 6 environment variables have been properly set (stuck a console.log in app.js), but whenever I attempt to access /setup I get 

```
[SyntaxError: Unexpected token  ]
```

So I tried setting up the heroku instance. It spins up, but when I access /setup both  `/api/setup/workspace` and `/api/setup/activities` return status 500 with 

```
 {"status":401,"message":"Authentication Error - invalid username","code":20003,"moreInfo":"https://www.twilio.com/docs/errors/20003"}
```

I double checked all my ids and secrets, and everything seems to be in order.

**Comment by nash-md** [comment]
Hi Dylan,

I guess you installed it on your own server? I ran into the same issue
yesterday, the problem was an invalid configuration template, it is fixed
now. Can you update your code and try again?

The project needs both, the auth token + account sid, and the api key
- api secret for the ip messaging part, is it possible you mixed both up?

Thanks

Matthias

On Fri, May 27, 2016 at 11:54 PM, DylanNWatt notifications@github.com
wrote:

> I've been attempting to get the demo up and running, but seem to be
> running into some issues with the initial configuration. I initially tried
> to set up the server locally. All 6 environment variables have been
> properly set (stuck a console.log in app.js), but whenever I attempt to
> access /setup I get
> 
> [SyntaxError: Unexpected token  ]
> 
> So I tried setting up the heroku instance. It spins up, but when I access
> /setup, /api/setup/workspace and /api/setup/activities both 500 with
> {"status":401,"message":"Authentication Error - invalid
> username","code":20003,"moreInfo":"
> https://www.twilio.com/docs/errors/20003"}
> 
> I double checked all my ids and secrets, and everything seems to be in
> order.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nash-md/twilio-contact-center/issues/1, or mute the
> thread
> https://github.com/notifications/unsubscribe/APPZL1mkXKzeQGraIoz82BQlfMg_CTqZks5qF-bCgaJpZM4IpA1i
> .

##

**Comment by DylanNWatt** [comment]
I pulled the latest into my fork, and everything seems to be working. Thanks!
