### ISSUE TITLE
error on setup

### ISSUE THREAD

**Issue by tbagalini** [nash-md/twilio-contact-center#17]
Oh snap!
{ "status": 400, "message": "VoiceUrl is not a valid URL: http://demo-contact-.herokuapp.com/api/ivr/welcome", "code": 21402, "moreInfo": "https://www.twilio.com/docs/errors/21402" }

**Comment by nash-md** [comment]
@tbagalini did you run the project on localhost? Twilio Voice requires an URL that can be reached by the public internet. Can you provide me details which URL you were using?

There is a note in the readme under the **Manual Install - On Your Own Server** section about it.
