### ISSUE TITLE
Local Setup -  "status": 400, "message": "Missing required parameter FriendlyName in the post body"

### ISSUE THREAD

**Issue by skwid138** [nash-md/twilio-contact-center#18]
I received the following Error attempting to Save Settings during a local setup. It's been resolved, but I wanted to post in case anyone else runs into the same issue. 

````
Oh snap!
{ 
    "status": 400,
    "message": "Missing required parameter FriendlyName in the post body",
    "code": 20001,
    "moreInfo": "https://www.twilio.com/docs/errors/20001"
}
````

I resolved it by adding the following keys to my .env

`TWILIO_CHAT_SERVICE_SID = "ISxxx..."`
`TWILIO_API_KEY_SID = "SKxxx..."`
`TWILIO_API_KEY_SECRET = "xxx..."`

Initially I thought these were optional unless you wanted to use Chat or Video, but it appears they're needed regardless.

**Comment by nash-md** [comment]
This issue is fixed.
