### ISSUE TITLE
Twilio Debug Error 16011 - Outbound calls

### ISSUE THREAD

**Issue by skwid138** [nash-md/twilio-contact-center#20]
This has been resolved, but I wanted to post just in case anyone else runs into this issue. 

While making outbound calls from the client Twilio's debugger was showing an error code of 16011

"Got HTTP 500 response from https://47c30956.ngrok.io/api/phone/call/CA7e139f760ff6996fb905c6ec79f298f6/add-participant/12345678900"

Node was logging the following
```` 
{
    status: 403,
    message: "Access Denied",
    code: 12400,
    moreInfo: "https://www.twilio.com/docs/errors/12400",
    detail: undefined
}
````

I was able to resolve the issue by updating my Twilio conference settings from Twilio Conference to Agent Conference.
https://www.twilio.com/console/voice/conferences/settings

**Comment by nash-md** [comment]
Comment to activate agent conference was added to the readme.
