### ISSUE TITLE
Error on Setup 20001

### ISSUE THREAD

**Issue by AnthonySLWhite** [nash-md/twilio-contact-center#23]
While doing the setup both manually and with heroku, I'm having the same issues. An error message appears that says:

```
{ 
[Error: Queue named Chat Queue Testing already exists for workspace WS5a372d5824277c2bb4759f8b525c7ae3 for account ACa7acfd5f1b6f961eaf664b7107de54d0]
  status: 400,  message:
   'Queue named Chat Queue Testing already exists for workspace WS5a372d5824277c2bb4759f8b525c7ae3 for account ACa7acfd5f1b6f961eaf664b7107de54d0',
  code: 20001,
  moreInfo: 'https://www.twilio.com/docs/errors/20001',
  detail: undefined 
}
```

I changed nothing on the code, I only setted the environment variables.
I tried deleting the queues but nothing changed.
What can be causing this?

**Comment by nash-md** [comment]
Please always install on a TaskRouter Workspace without any queues and workflows. The setup tries to create it and this fails in your setup. Install on an empty Workspace and with the template `configuration.json` provided.
