### ISSUE TITLE
node js app workspace error

### ISSUE THREAD

**Issue by mickstevens** [nash-md/twilio-contact-center#25]
This runs fine in heroku but when trying the node/ngrok version the following errors seen in browser & terminal. Have checked WS ID correct in console & .env ok

browser error:

<img width="290" alt="oh_snap" src="https://user-images.githubusercontent.com/1260281/64716292-06869680-d4ba-11e9-9ded-6849a4e3ed2f.png">

terminal error:

{ [Error: The requested resource /Workspaces/WS********************************/Workers was not found]
  status: 404,
  message: 'The requested resource /Workspaces/WS********************************/Workers was not found',
  code: 20404,
  moreInfo: 'https://www.twilio.com/docs/errors/20404',
  detail: undefined }

Rgds, Mick

P.S. 500 seen from ngrok terminal output:

POST /api/validate/setup       500 Internal Server Error

which I think is being generated from /twilio-contact-center/controllers/validate.js ?

**Comment by nash-md** [comment]
Please check the API key & secret, AccountSid and the TaskRouter Workspace, one of the values must be different to your Heroku setup.
