### ISSUE TITLE
Phone dialing hits IVR endpoint everytime

### ISSUE THREAD

**Issue by BRafols** [nash-md/twilio-contact-center#26]
With a new installation, when I test the phone dialer and press call, what I hear is the IVR.

Looks to me like the TwiML app will route all `inboud` and `outbound` calls thought the TwiML enpoint.

Am I doing something wrong?

**Comment by nash-md** [comment]
@BRafols, apologies for the very late response. Are you calling a valid E.164 phone number from the dial pad? In case you call an invalid number you would just hear the conference waiting music and the dial to the phone number fails. 

The frontend and backend does not check for a valid phone number, I'll add a check for it.
