### ISSUE TITLE
Consider port to Angular 8

### ISSUE THREAD

**Issue by jstallm** [nash-md/twilio-contact-center#27]
I'm curious if there has been any talk about porting this application to the latest angular 8. 

The first commit to master was May 2016, when Angular was at 1.x

I'd just imagine a large group of engineers interested in learning about twilio services though an angular 8 example using typescript. Similar to those who learned about twilio using this repo, just those engineers that are just coming into contact with the twilio landscape now, in 2020

**Comment by nash-md** [comment]
Yes, 100% agree that AngularJS feels out of date these days. There were a few questions in the past if this project could be ported to a new Angular, Vue or React frontend. This would require a full rewrite of the frontend part though.

The main purpose of this project was to give engineers a baseline and and a working demo. In case there is a major product upgrade on Twilio, for instance TaskRouter a rewrite might be an option, right now this project is primarily maintained with minor upgrades on features and fixed.
