### ISSUE TITLE
Some files are missing.

### ISSUE THREAD

**Issue by aquatec9256** [nash-md/twilio-contact-center#29]
I have setup the contact center on the given domain
https://talk.myceo.com/
facing a lot of issues its saying that files are missing (given 404 error)
please check the given screenshot
![image](https://user-images.githubusercontent.com/55432822/81824543-36a79d00-9553-11ea-93a3-154e503f5920.png)
![download (1)](https://user-images.githubusercontent.com/55432822/81824652-5939b600-9553-11ea-9850-6e2400b3f599.png)

**Comment by nash-md** [comment]
The home page has a basic check, was there any error on the right displayed? Did you run /setup?
