### ISSUE TITLE
Dead .js scripts from Twilio CDN and SSL req of Twilio

### ISSUE THREAD

**Issue by TechDevLab** [nash-md/twilio-contact-center#32]
First off, thank you for the detailed sample project.  I am following along, but running into a few issues.  I am installing it on a web server I run, GC, and using LetsEncrypt.  Without HTTPS, Twilio is no longer allowing calls to be made.  I think I got everything set up correctly, but getting the following in debug console of firefox.  Tested the dialer, and the button seems to not function anymore.  Could you offer any guidance?  Thanks

`Loading failed for the <script> with source “https://media.twiliocdn.com/sdk/js/client/v1.7/twilio.min.js”. 
workplace.html:282:1
Loading failed for the <script> with source “https://media.twiliocdn.com/taskrouter/js/v1.20/taskrouter.min.js”. workplace.html:283:1
Loading failed for the <script> with source “https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js”. workplace.html:284:1
Loading failed for the <script> with source “https://media.twiliocdn.com/sdk/js/chat/v3.3/twilio-chat.min.js”. workplace.html:285:1
Loading failed for the <script> with source “https://media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js”. workplace.html:287:1`

**Comment by nash-md** [comment]
The JS scripts mentioned in your post can be loaded from my instance without any issue. Yes, most browsers do not allow WebRTC without an encrypted connection, the app displays an error if you load it on a unencrypted protocol, in addition it is mentioned in the README.

Please test the demo project with SSL, for example host it on Heroku.
