### ISSUE TITLE
TWILIO_WORKSPACE_SID value not working

### ISSUE THREAD

**Issue by tgraffix** [nash-md/twilio-contact-center#33]
I was almost successful in getting the app set up, but the TWILIO_WORKSPACE_SID value in the config (which does match my Twilio settings) doesn't work.  (I followed the instructions precisely, and triple checked everything)

```
Oh snap!
The environment variable TWILIO_WORKSPACE_SID is not set or incorrect. If you are on Heroku please update your application settings.

```
Maybe something has changed at Twilio? (possibly additional settings inside of Twilio -- perhaps to Channels or Workers or something?)

Thanks!

**Comment by nash-md** [comment]
The workspaceSid starts with **WS...**, are you sure you copied the right Sid from https://www.twilio.com/console/taskrouter/dashboard to the settings? The error is returned if this expression is true `!process.env.TWILIO_WORKSPACE_SID || process.env.TWILIO_WORKSPACE_SID.length !== 34`

**Comment by tgraffix** [comment]
Thanks for the quick reply. :)
Yes, 34 chars copied/pasted from Workspace properties page:

![chrome_2FM7RSMjE4](https://user-images.githubusercontent.com/8551903/101515467-fde27180-3943-11eb-98da-f7641fc19e1d.png)
![SecureCRT_Gn1nrmJc1g](https://user-images.githubusercontent.com/8551903/101515475-00dd6200-3944-11eb-8d86-41e3a8d756ec.png)

**Comment by nash-md** [comment]
Can you try to open **/setup** on your installation and check if it correctly fetches the Twilio Workspace? The error message is just a notification to know something is wrong.

**Comment by tgraffix** [comment]
Sure thing.  When accessing the /setup page, I get a similar error message.  And here's what the console looks like. (just a temporary dev server, so I don't mind having the URLs in the screenshot)  :P 
![chrome_Xs7ohHWbT5](https://user-images.githubusercontent.com/8551903/101519988-7697fc80-3949-11eb-9de9-e2af0780e296.png)
![SecureCRT_EnJjOdSmps](https://user-images.githubusercontent.com/8551903/101520001-7ac41a00-3949-11eb-9862-36cae1166c58.png)

**Comment by nash-md** [comment]
As you can see from your debug log, the **workspaceSid** is **undefined**, please check your current settings, either the **.env** file or the way you initialise the variables is wrong. I checked with my setup, and it worked without any issue.

I would recommend debugging it locally and ensure **process.env.TWILIO_WORKSPACE_SID** is available to the Node server.

**Comment by tgraffix** [comment]
Noted!  I'll get to work on that.  Thanks!

**Comment by tgraffix** [comment]
Success!  Looks like I simply needed to add those yaml vars to .env.
(I'm very new to APIs, frameworks, etc. btw!)

Thanks!!! =D
