### ISSUE TITLE
Missing application SID

### ISSUE THREAD

**Issue by brettev** [nash-md/twilio-contact-center#5]
Error on logging in from twilio.min.js:49
code: 31100
message: "Missing application SID"

I've got the env var set up right. Seems like it might be required somewhere else? Do I need to monkey with the app.json to include the keys or something?

**Comment by nash-md** [comment]
It looks like the setup has not been completed yet. The application Sid is created automatically during setup. Please open **http://[your_application_name]/setup**, configure the worker states and the phone number.
