### ISSUE TITLE
Unable to setup due to invalid SmsUrl

### ISSUE THREAD

**Issue by ilDon** [nash-md/twilio-contact-center#6]
When attempting to setup the application, I get the following error

    {"status":400,"message":"SmsUrl is not valid: http://localhost/api/messaging-adapter/inbound","code":21402,"moreInfo":"https://www.twilio.com/docs/errors/21402"}

As I only need to test IP chat, and I'd like to do so in localhost (so unreachable url), can I bypass this somehow? Or how can I fix it?

**Comment by nash-md** [comment]
Theoretically it could run on localhost but there are several parts (Twilio Taskrouter Assignment Callback, IP Chat Webhooks, Phone Number Request Url) that require a public Url right now. I would suggest you use a tool that creates a secure tunnel to localhost, for instance https://ngrok.com/

If you want to run it on localhost the following parts need to be changed in the setup controller:
- skip the part that configures the phone number and the Twilio application
- the Twilio Taskrouter assignment callback needs to be removed or a url that returns http 200
- the IP Chat Webhooks.OnMessageSent must not be set

**Comment by aoberko** [comment]
I am having the same issue and I am using ngrok, but any time I try saving the setup it still sends 'VoiceURL: http://localhost/api/agents/call' to twilio. please where do i replace the localhost with the ngrok url in the code.

**Comment by nash-md** [comment]
You need to open the project in your browser via the ngrok public url instead of localhost.
