### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by nkmhandels** [nash-md/twilio-contact-center#7]
Hi,
great git, congrats. How can i change the language because it set to default "men" "en-EN" and i would like to change it for eg. "female" "de-DE". Tried to change the configuration.json but without success.

Thanks

**Comment by nash-md** [comment]
Changing the language via configuration is not possible. If you want to set the language of the IVR, you need to change `controllers/ivr.js` and set the text-to-speech language there.

Possible options for the TwiML `<Say>`  are documented on page https://www.twilio.com/docs/api/twiml/say

**Comment by nkmhandels** [comment]
Hi,

i tried to modify the ivr.js to: 
// redirect the call to the previous twiml
		twiml.say({voice:'woman'}, 'Your selection was not valid, please try again')
				twiml.pause({length: 2})
		twiml.redirect({ method: 'GET' }, 'welcome')


and

function (node) {
			node.say({voice:'woman',language:'de-DE'},'Press any key if you want a callback, if you want to talk to an agent please wait in the line')



and

var attributes = {
			say:({voice:'woman',language:'de-DE'}, 'Caller answered IVR with option "' + team.friendlyName + '"'),
			gender:'male',
			language:'de-DE',
			channel: 'phone',
			phone: req.query.From,
			name: req.query.From,
			title: 'Inbound call',
			type: 'inbound_call',
			team: team.id


but nothing happened, still the same male voice by default. any suggestions are welcomed!

Thanks

**Comment by SilvaFilipe** [comment]
Hi, I have the same problem. How can i change the voice language? Help please. Ty :)
