### ISSUE TITLE
Invalid Phone Number

### ISSUE THREAD

**Issue by davidjordan235** [nash-md/twilio-contact-center#9]
Ok, well I seemed to be able to get it to login, however, the agent login isn't changing the agent status to available when you login.

Thank you,

**Comment by nash-md** [comment]
Please check the JS console in your browser if there is any error with your WS socket to Twilio Taskrouter. After you logged-in as the agent you can open the worker dashboard on the Twilio Console and check if the corresponding worker is set to idle.
